/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#e5e1e4",
        "outline-variant": "#444653",
        "on-primary-container": "#8ea6ff",
        "surface-tint": "#b6c4ff",
        "secondary-fixed-dim": "#ffb3b1",
        "surface-container-low": "#1c1b1d",
        "on-secondary-fixed": "#410007",
        "surface": "#131315",
        "surface-container-high": "#2a2a2c",
        "on-secondary": "#680011",
        "on-tertiary-container": "#a9aaaa",
        "primary-fixed-dim": "#b6c4ff",
        "secondary": "#ffb3b1",
        "tertiary": "#c6c6c7",
        "surface-dim": "#131315",
        "primary-fixed": "#dce1ff",
        "on-secondary-fixed-variant": "#92001d",
        "on-error": "#690005",
        "on-tertiary": "#2f3131",
        "inverse-primary": "#3456c1",
        "on-surface": "#e5e1e4",
        "inverse-on-surface": "#313032",
        "surface-variant": "#353437",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-surface-variant": "#c4c5d5",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "tertiary-container": "#3d3f3f",
        "outline": "#8e909e",
        "on-secondary-container": "#ffe7e5",
        "surface-container-highest": "#353437",
        "primary": "#b6c4ff",
        "surface-bright": "#39393b",
        "on-primary": "#00277f",
        "surface-container": "#201f21",
        "primary-container": "#0033a0",
        "on-tertiary-fixed": "#1a1c1c",
        "on-primary-fixed": "#001550",
        "background": "#131315",
        "surface-container-lowest": "#0e0e10",
        "tertiary-fixed": "#e2e2e2",
        "secondary-container": "#d6042f",
        "on-primary-fixed-variant": "#133ca8",
        "error": "#ffb4ab",
        "on-tertiary-fixed-variant": "#454747",
        "on-background": "#e5e1e4",
        "secondary-fixed": "#ffdad8"
      }
    },
  },
  plugins: [],
}
